### ISSUE TITLE
Import CSV - Presets for Google contacts and Outlook

### ISSUE THREAD

**Issue by dandaandaaaaaan** [AY2122S2-CS2103-W17-1/tp#147]
Extension of #92

The command should be able to take in a preset to import Google contacts and outlook contacts exported csv.

Sub tasks:
- Need to modify to allow for potentially empty fields @sharpstorm will need advise if i should do this
    - Name doesn't need to allow empty but have to modify phone/email/address for sure

Google Contacts:
- Due to "dynamic" nature of the fields that are generated, need to check for which column holds details such as Phone number/email, etc.

Outlook Contacts:
- Fields are in default places, so this should be pretty simple to implement, but first name and last name field content need to be combined in order to put into the "Name" column.

Potential upgrade:
- Support for contact vcard importing (used by Apple devices)

**Comment by sharpstorm** [comment]
I think having empty fields can be explored, but since this is an application for tracking contact information, either phone or email (or both) must be present.

**Comment by dandaandaaaaaan** [comment]
ok i agree with the idea of either phone or email also. I think a potential for placeholder content for if anything is empty can be text in a more darker font such that it somewhat blends into the background. I did a quick mockup, something like this 
![Screenshot 2022-03-09 at 3 26 57 PM](https://user-images.githubusercontent.com/13099969/157394452-0ce0d2c8-b560-4e5d-ad50-240cbe04b85c.png)

Text colour used in this mockup (for ref in case to implement): 888b8c
I choose a colour like this such that the text would be visible enough despite the 3 different potential colours of the background

**Comment by dandaandaaaaaan** [comment]
Does it make sense to further add on options in the `importcsv` command? Would it be kind of confusing to use?

current format: `importcsv f/FILEPATH [n/COLUMNNUM] [p/COLUMN_PERSON] [e/COLUMN_EMAIL] [a/COLUMN_ADDRESS] [t/COLUMN_TAGS]`

proposed format: `importcsv f/FILEPATH [format/FORMATOPTION] [n/COLUMNNUM] [p/COLUMN_PERSON] [e/COLUMN_EMAIL] [a/COLUMN_ADDRESS] [t/COLUMN_TAGS]`

FORMATOPTION = 1 - default
FORMATOPTION = 2 - google
FORMATOPTION = 3 - outlook

another potential option is to do a separate command
`importformattedcsv f/FILEPATH format/FORMATOPTION`
this would then handle the importing of google/outlook formatted csvs naturally
 
cc: @sharpstorm

**Comment by sharpstorm** [comment]
> ok i agree with the idea of either phone or email also. I think a potential for placeholder content for if anything is empty can be text in a more darker font such that it somewhat blends into the background. I did a quick mockup, something like this ![Screenshot 2022-03-09 at 3 26 57 PM](https://user-images.githubusercontent.com/13099969/157394452-0ce0d2c8-b560-4e5d-ad50-240cbe04b85c.png)

In terms of the mockup, I my opinion is that phone and email should be adjacent (i.e. move address down), and that address can be empty (no need for placeholder here since its the last item).



> Does it make sense to further add on options in the `importcsv` command? Would it be kind of confusing to use?
> 
> current format: `importcsv f/FILEPATH [n/COLUMNNUM] [p/COLUMN_PERSON] [e/COLUMN_EMAIL] [a/COLUMN_ADDRESS] [t/COLUMN_TAGS]`
> 
> proposed format: `importcsv f/FILEPATH [format/FORMATOPTION] [n/COLUMNNUM] [p/COLUMN_PERSON] [e/COLUMN_EMAIL] [a/COLUMN_ADDRESS] [t/COLUMN_TAGS]`

I think keeping it as a combined command is acceptable, but you should validate that you either take a predefined format, or custom columns.

**Comment by dandaandaaaaaan** [comment]
this going to likely take a backseat, export more important

**Comment by dandaandaaaaaan** [comment]
closing since I think we won't do this as an explicit feature anymore, and what we have is sufficient
