### ISSUE TITLE
Refactor Person-Tag Integrity Enforcement

### ISSUE THREAD

**Issue by sharpstorm** [AY2122S2-CS2103-W17-1/tp#160]
## Current Issue
- Currently, the synchronization between the persons and tags in the `AddressBook` is handled at the Logic component. This requires all functions modifying either persons or tags to ensure maintenance of both lists, which can cause bugs and result in an inconsistent Model instance if either is done incorrectly.

## Proposed Change
- The integrity enforcement should be shifted to the Model component, which provides a tighter integrity enforcement and will never allow the Model to be in an inconsistent state.
- This would entail the following changes in `Model`
  - `addPerson()` adding new tags to the tag list
  - `setPerson()` updates the tag list based on removals / additions of tags
  - `deletePerson()` removing tags from the tag list
  - `deleteTag()` removes the deleted tag from all Persons
  - `setTag()` updates the tags in all Persons with the old Tag

**Comment by KwanHW** [comment]
In the case of `deletePerson()`, I like to would suggest we do not remove tags from the tag.
