### ISSUE TITLE
Range Command does not Support Parameter Reordering

### ISSUE THREAD

**Issue by sharpstorm** [AY2122S2-CS2103-W17-1/tp#188]
## Synopsis
The `Range` Command fails if the `to/` parameter appears before `from/`, even though that is allowed in the specification.

**Comment by HanJiyao** [comment]
reordering is support in latest pr, ordering from to is working, but "edit a/..." need to be stick together

**Comment by dandaandaaaaaan** [comment]
functionality is fixed from #223 verified. slight issues with the range command syntax and messages, but I will file separate ticket for this (quite minor bugs)
