### ISSUE TITLE
Chain Command Modifying Unexpected Index

### ISSUE THREAD

**Issue by sharpstorm** [AY2122S2-CS2103-W17-1/tp#194]
## Synopsis
The `chain` command has been observed to be accepting the wrong index for particular combinations of commands. For example, `chain add ... && delete 5` deletes the person at index `4` instead. This is to be investigated.

**Comment by HanJiyao** [comment]
this should fix in latest pull request, please check

**Comment by dandaandaaaaaan** [comment]
just checked, this works now. thanks for fixing
