### ISSUE TITLE
Test Import and Export Feature

### ISSUE THREAD

**Issue by sharpstorm** [AY2122S2-CS2103-W17-1/tp#196]
## Issue to be Investigated
The import and export functionality can be inconsistent and unpredictable at times. It should be tested further.

**Comment by dandaandaaaaaan** [comment]
I think i resolved it already previously, may have encountered error when I was testing for the demo by using a wrongly formatted file, thus resulting in me raising the issue during the meeting.

Just tested the flow of
- export contacts as CSV
- delete all contacts in the `.json`
- import back

all contacts are correctly imported, along with their respective tags
Some of the entries do not have tags on them, but they are still properly added without tags.
