### ISSUE TITLE
Bugs - Range command

### ISSUE THREAD

**Issue by dandaandaaaaaan** [AY2122S2-CS2103-W17-1/tp#224]
# Issue

The range command works but I noticed a few issues while testing
1. The example text is wrong, it should be something along the lines of
`range editperson a/Address For Persons 1 to 3 from/1 to/3`
<img width="754" alt="Screenshot 2022-03-24 at 7 34 02 PM" src="https://user-images.githubusercontent.com/13099969/159907797-214e075f-1adf-499d-b6e0-d80d1b27b111.png">

2. If a invalid param is passed through (i.e, phone number of 1 digit) , an exception happens

usually, if you do an `editperson 2 p/1` it will show smth like this
<img width="815" alt="Screenshot 2022-03-24 at 7 38 42 PM" src="https://user-images.githubusercontent.com/13099969/159908498-05ebd97d-6d08-4e1f-a041-4e74071bd979.png">

however, if a similar operation is performed using range, it somehow defaults to the normal invalid command error. i can see how this may be a more complicated fix 

https://user-images.githubusercontent.com/13099969/159909041-4f27bdf2-1a02-4724-89b9-3947c2235681.mov

3. number parse exception if parse in alphabets into the `from/` and `to/`. should be a pretty simple fix, but this one most impt to fix as it causes exception 
<img width="1126" alt="Screenshot 2022-03-24 at 7 44 11 PM" src="https://user-images.githubusercontent.com/13099969/159909385-678a0665-1084-4235-81e0-4527f4f39a20.png">

**Comment by HanJiyao** [comment]
These 3 issues has been solved in latest PR
