### ISSUE TITLE
[PE-D] Phone number takes in too many digits

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-1/tp#271]
The phone number portion of the user class takes in an unlimited number of digits, which can lead to errors when adding numbers into the address book

![Screenshot 2022-04-01 at 2.14.13 PM.png](https://raw.githubusercontent.com/iztanpy/ped/main/files/ba0ba315-68c8-468d-83f8-d4dc6a9a8f37.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: iztanpy/ped#1

**Comment by dandaandaaaaaan** [comment]
# Not a bug

We did not want to limit the digits to be too low. Will probably need to double check what the limit actually is
