### ISSUE TITLE
[PE-D] Unclear on whether name field is name of person or name of appointment

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-1/tp#285]
![Screenshot 2022-04-01 at 2.31.41 PM.png](https://raw.githubusercontent.com/markbiju/ped/main/files/22dc1f7f-cd11-4fe4-8d84-acfc55d8462a.png)

Could be clearer whether name field is name of appointment or name of person

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: markbiju/ped#5

**Comment by sharpstorm** [comment]
# Not a Bug

We consider this not a bug, as it is implied that if the `Person:` field is the person, then the `Name:` field can no longer be the person's name.
