### ISSUE TITLE
[PE-D] Incorrect error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-1/tp#291]
duration is a positive int, but just a too large number 

![Screenshot 2022-04-01 at 2.41.05 PM.png](https://raw.githubusercontent.com/zxgoh/ped/main/files/9b3d8691-2ab4-408e-970d-d4a8d1067656.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zxgoh/ped#6

**Comment by sharpstorm** [comment]
Similar to #273.

**Comment by sharpstorm** [comment]
Cannot be changed under a feature freeze, but the user guide will be updated to reflect integer limitations.
