### ISSUE TITLE
[PE-D] Error in recording and checking for invalid email

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-1/tp#295]
![Screenshot 2022-04-01 at 2.50.48 PM.png](https://raw.githubusercontent.com/iztanpy/ped/main/files/bda94b15-cdd0-45d9-bbbb-88bfe2698c86.png)
Email allows invalid email format 'betsycrowe@com', without the domain portion

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: iztanpy/ped#6

**Comment by sharpstorm** [comment]
Referring to SMTP Specifications [RFC 5321 Section 2.3.5](https://datatracker.ietf.org/doc/html/rfc5321#section-2.3.5), domain names may be dotless, in other words, does not require a subdomain component. This may be the case for TLD level email addresses or local networks where domains are likewise dotless. In particular, the document states

> A domain name (or often just a "domain") consists of one or more components, separated by dots if more than one appears.  In the case of a top-level domain used by itself in an email address, a single string is used without any dots.

This is corroborated by [Wikipedia](https://en.wikipedia.org/wiki/Email_address#Examples) and [HTML Email Input Validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email), which indicates that the email address above `betsycrowe@com` is indeed a valid email address.

Would love to hear inputs from the rest @dandaandaaaaaan @KwanHW @Wei-Xinn @HanJiyao.
