### ISSUE TITLE
[PE-D] Cannot find exported csv file

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-1/tp#296]
Unable to locate the `data` directory as described in the UG

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: zxgoh/ped#8

**Comment by sharpstorm** [comment]
To be tested on Linux for security policy.

**Comment by dandaandaaaaaan** [comment]
Just double checked again, confirmed working on Mac if run via `java -jar contax.jar`

If tester is on Mac and double clicked to run, the saved files are saved in a directory that is hidden within the MacOS file system. This is a Mac issue and there is no way I can do anything about it. Documented on the UG for Mac users to specifically remember to run via the command.

To test on Linux if similar issue happens.

**Comment by dandaandaaaaaan** [comment]
Upon checking the default filepath if run via double click, it seems that its in some hidden folder that I have no control of
![Screenshot 2022-04-04 at 2 47 56 PM](https://user-images.githubusercontent.com/13099969/161488277-ffa38a57-f165-4999-8f3e-284f3b9d12cf.png)
.

**Comment by KwanHW** [comment]
Works on Manjaro Linux

**Comment by dandaandaaaaaan** [comment]
Works on linux, so it's a Mac specific issue. All testers should run the `.jar` file via the command, we have no control to fix the double click to open the `.jar` issue.
